apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dqa-petclinic.fullname" . }}
  labels:
    {{- include "dqa-petclinic.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dqa-petclinic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dqa-petclinic.selectorLabels" . | nindent 8 }}
    spec:
      nodeSelector:
	{{- if .Values.nodeSelector }}
        {{- toYaml .Values.nodeSelector | nindent 8 }}
	{{- end }}
      serviceAccountName: {{ include "dqa-petclinic.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: MYSQL_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-url
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-user
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password
