apiVersion: v1
kind: Service
metadata:
  name: {{ include "dqa-petclinic.fullname" . }}
  labels:
    {{- include "dqa-petclinic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    {{- include "dqa-petclinic.selectorLabels" . | nindent 4 }}
